package ezc.model;
// Generated 28 Apr, 2020 9:39:29 PM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EzcPoAcknowledgement generated by hbm2java
 */
@Entity
@Table(name = "EZC_PO_ACKNOWLEDGEMENT")
public class EzcPoAcknowledgement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "EZPA_DOC_NO", unique = true, nullable = false, length = 10)
	private String ezpaDocNo;
	@Column(name = "EZPA_SYS_KEY", length = 18)
	private String ezpaSysKey;
	@Column(name = "EZPA_SOLD_TO", length = 10)
	private String ezpaSoldTo;
	@Column(name = "EZPA_DOC_DATE")
	private Date ezpaDocDate;
	@Column(name = "EZPA_DOC_STATUS", length = 1)
	private Character ezpaDocStatus;
	@Column(name = "EZPA_CREATED_ON")
	private Date ezpaCreatedOn;
	@Column(name = "EZPA_CREATED_BY", length = 10)
	private String ezpaCreatedBy;
	@Column(name = "EZPA_MODIFIED_ON")
	private Date ezpaModifiedOn;
	@Column(name = "EZPA_HEADER_TEXT", nullable = false, length = 65535, columnDefinition="TEXT")
	private String ezpaHeaderText;
	@Column(name = "EZPA_EXT1", length = 20)
	private String ezpaExt1;
	@Column(name = "EZPA_EXT2", length = 20)
	private String ezpaExt2;
	@Column(name = "EZPA_EXT3", length = 20)
	private String ezpaExt3;

	public EzcPoAcknowledgement() {
	}

	

	public String getEzpaDocNo() {
		return this.ezpaDocNo;
	}

	public void setEzpaDocNo(String ezpaDocNo) {
		this.ezpaDocNo = ezpaDocNo;
	}

	public String getEzpaSysKey() {
		return this.ezpaSysKey;
	}

	public void setEzpaSysKey(String ezpaSysKey) {
		this.ezpaSysKey = ezpaSysKey;
	}

	public String getEzpaSoldTo() {
		return this.ezpaSoldTo;
	}

	public void setEzpaSoldTo(String ezpaSoldTo) {
		this.ezpaSoldTo = ezpaSoldTo;
	}

	public Date getEzpaDocDate() {
		return this.ezpaDocDate;
	}

	public void setEzpaDocDate(Date ezpaDocDate) {
		this.ezpaDocDate = ezpaDocDate;
	}

	public Character getEzpaDocStatus() {
		return this.ezpaDocStatus;
	}

	public void setEzpaDocStatus(Character ezpaDocStatus) {
		this.ezpaDocStatus = ezpaDocStatus;
	}

	public Date getEzpaCreatedOn() {
		return this.ezpaCreatedOn;
	}

	public void setEzpaCreatedOn(Date ezpaCreatedOn) {
		this.ezpaCreatedOn = ezpaCreatedOn;
	}

	public String getEzpaCreatedBy() {
		return this.ezpaCreatedBy;
	}

	public void setEzpaCreatedBy(String ezpaCreatedBy) {
		this.ezpaCreatedBy = ezpaCreatedBy;
	}

	public Date getEzpaModifiedOn() {
		return this.ezpaModifiedOn;
	}

	public void setEzpaModifiedOn(Date ezpaModifiedOn) {
		this.ezpaModifiedOn = ezpaModifiedOn;
	}

	public String getEzpaHeaderText() {
		return this.ezpaHeaderText;
	}

	public void setEzpaHeaderText(String ezpaHeaderText) {
		this.ezpaHeaderText = ezpaHeaderText;
	}

	public String getEzpaExt1() {
		return this.ezpaExt1;
	}

	public void setEzpaExt1(String ezpaExt1) {
		this.ezpaExt1 = ezpaExt1;
	}

	public String getEzpaExt2() {
		return this.ezpaExt2;
	}

	public void setEzpaExt2(String ezpaExt2) {
		this.ezpaExt2 = ezpaExt2;
	}

	public String getEzpaExt3() {
		return this.ezpaExt3;
	}

	public void setEzpaExt3(String ezpaExt3) {
		this.ezpaExt3 = ezpaExt3;
	}

}
