package ezc.model;
// Generated 27 Apr, 2020 10:26:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EzcUsers generated by hbm2java
 */
@Entity
@Table(name = "ezc_users")
public class EzcUsers implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String euId;
	private char euDeletionFlag;
	private String euFirstName;
	private String euMiddleInitial;
	private String euLastName;
	private String euEmail;
	/*
	 * private String euCreatedDate; private String euChangedDate; private String
	 * euChangedBy; private String euValidToDate; private String euLastLoginTime;
	 * private String euLastLoginDate;
	 */
	private String euPassword;
	private Integer euType;
	//private short eugId;
	private String euBusinessPartner;
	//private Character euIsBuiltInUser;
	//private Long euCurrentNumber;

	public EzcUsers() {
	}

	

	@Id

	@Column(name = "EU_ID", unique = true, nullable = false, length = 10)
	public String getEuId() {
		return this.euId;
	}

	public void setEuId(String euId) {
		this.euId = euId;
	}

	@Column(name = "EU_DELETION_FLAG", nullable = false, length = 1)
	public char getEuDeletionFlag() {
		return this.euDeletionFlag;
	}

	public void setEuDeletionFlag(char euDeletionFlag) {
		this.euDeletionFlag = euDeletionFlag;
	}

	@Column(name = "EU_FIRST_NAME", nullable = false, length = 60)
	public String getEuFirstName() {
		return this.euFirstName;
	}

	public void setEuFirstName(String euFirstName) {
		this.euFirstName = euFirstName;
	}

	@Column(name = "EU_MIDDLE_INITIAL", length = 3)
	public String getEuMiddleInitial() {
		return this.euMiddleInitial;
	}

	public void setEuMiddleInitial(String euMiddleInitial) {
		this.euMiddleInitial = euMiddleInitial;
	}

	@Column(name = "EU_LAST_NAME", nullable = false, length = 60)
	public String getEuLastName() {
		return this.euLastName;
	}

	public void setEuLastName(String euLastName) {
		this.euLastName = euLastName;
	}

	@Column(name = "EU_EMAIL", length = 40)
	public String getEuEmail() {
		return this.euEmail;
	}

	public void setEuEmail(String euEmail) {
		this.euEmail = euEmail;
	}

	/*
	 * @Column(name = "EU_CREATED_DATE", length = 10) public String
	 * getEuCreatedDate() { return this.euCreatedDate; }
	 * 
	 * public void setEuCreatedDate(String euCreatedDate) { this.euCreatedDate =
	 * euCreatedDate; }
	 * 
	 * @Column(name = "EU_CHANGED_DATE", length = 10) public String
	 * getEuChangedDate() { return this.euChangedDate; }
	 * 
	 * public void setEuChangedDate(String euChangedDate) { this.euChangedDate =
	 * euChangedDate; }
	 * 
	 * @Column(name = "EU_CHANGED_BY", length = 10) public String getEuChangedBy() {
	 * return this.euChangedBy; }
	 * 
	 * public void setEuChangedBy(String euChangedBy) { this.euChangedBy =
	 * euChangedBy; }
	 * 
	 * @Column(name = "EU_VALID_TO_DATE", length = 10) public String
	 * getEuValidToDate() { return this.euValidToDate; }
	 * 
	 * public void setEuValidToDate(String euValidToDate) { this.euValidToDate =
	 * euValidToDate; }
	 * 
	 * @Column(name = "EU_LAST_LOGIN_TIME", length = 20) public String
	 * getEuLastLoginTime() { return this.euLastLoginTime; }
	 * 
	 * public void setEuLastLoginTime(String euLastLoginTime) { this.euLastLoginTime
	 * = euLastLoginTime; }
	 * 
	 * @Column(name = "EU_LAST_LOGIN_DATE", length = 10) public String
	 * getEuLastLoginDate() { return this.euLastLoginDate; }
	 * 
	 * public void setEuLastLoginDate(String euLastLoginDate) { this.euLastLoginDate
	 * = euLastLoginDate; }
	 */
	@Column(name = "EU_PASSWORD", nullable = false, length = 512)
	public String getEuPassword() {
		return this.euPassword;
	}

	public void setEuPassword(String euPassword) {
		this.euPassword = euPassword;
	}

	@Column(name = "EU_TYPE", nullable = false, precision = 1, scale = 0)
	public Integer isEuType() {
		return this.euType;
	}

	public void setEuType(Integer euType) {
		this.euType = euType;
	}

	/*
	 * @Column(name = "EUG_ID", nullable = false, precision = 3, scale = 0) public
	 * short getEugId() { return this.eugId; }
	 * 
	 * public void setEugId(short eugId) { this.eugId = eugId; }
	 */

	@Column(name = "EU_BUSINESS_PARTNER", nullable = false, length = 10)
	public String getEuBusinessPartner() {
		return this.euBusinessPartner;
	}

	public void setEuBusinessPartner(String euBusinessPartner) {
		this.euBusinessPartner = euBusinessPartner;
	}

	/*
	 * @Column(name = "EU_IS_BUILT_IN_USER", length = 1) public Character
	 * getEuIsBuiltInUser() { return this.euIsBuiltInUser; }
	 * 
	 * public void setEuIsBuiltInUser(Character euIsBuiltInUser) {
	 * this.euIsBuiltInUser = euIsBuiltInUser; }
	 */

	/*
	 * @Column(name = "EU_CURRENT_NUMBER", precision = 10, scale = 0) public Long
	 * getEuCurrentNumber() { return this.euCurrentNumber; }
	 * 
	 * public void setEuCurrentNumber(Long euCurrentNumber) { this.euCurrentNumber =
	 * euCurrentNumber; }
	 */

}
